dependencies:
#  "example:service/my-resource@0.1.0": target\wasm32-wasi\debug\bimpl.wasm
  "example:service/a-interface@0.1.0": target\wasm32-wasi\debug\aimpl.wasm
  "example:service/b-interface@0.1.0": target\wasm32-wasi\debug\bimpl.wasm
